version: '3'

services:
  diga-api-client:
    image: maven:3-jdk-11-slim
    container_name: diga-api-client
    volumes:
      - ./:/app/
    command: 'bash'
    working_dir: /app
    stdin_open: 'true'
    tty: 'true'